version: 0.2

env:
  parameter-store:
    COGNITO_REGION: '/${ENV}/accept/COGNITO_REGION'
    COGNITO_USER_POOL_ID: '/${ENV}/accept/COGNITO_USER_POOL_ID'
    COGNITO_CLIENT_ID: '/${ENV}/accept/COGNITO_CLIENT_ID'

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - cd client
      - npm install
      - cd ..
  build:
    commands:
      - npm run lint
      - npm run test
      - cd client
      - npm run test
      - cd ..
      - npm run build:client
      - npm run cognito:upload:customization
      - zip -q -r ${CODEBUILD_BUILD_ID}.zip package.json package-lock.json app.js app config public migrations

  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo "aws s3 cp ${CODEBUILD_BUILD_ID}.zip s3://${S3_EB_BUCKET}"
      - echo "eb deploy ..."
