import './SingUpFrom.scss';

import React from 'react';
// import { withFormik } from 'formik';

class SignUpForm extends React.Component {
  render() {
    return (
      <form className="sign-up__form">
        <div className="upload-photo" />
        <h5 className="sign-up__form__title">Personal info</h5>
        <p className="sign-up__form__description">
          This information is private and will not be visible to other users
        </p>
        <div className="sign-up__form__name">
          <div className="form-group">
            <label>First name</label>
            <input className="form-control" placeholder="" />
          </div>
          <div className="form-group">
            <label>Last name</label>
            <input className="form-control" placeholder="" />
          </div>
        </div>
        <div className="form-group">
          <label>Phone number</label>
          <small className="form-text text-muted">Enter your number</small>
          <input className="form-control" placeholder="" />
        </div>
        <div className="form-group">
          <label>Address</label>
          <small className="form-text text-muted">
            Enter a postcode or address line. Only information about your city will be visible to
            other users
          </small>
          <input className="form-control" placeholder="" />
        </div>
        <h5 className="sign-up__form__title">Public info</h5>
        <p className="sign-up__form__description">
          Your username is generated by the system. You can change it, this information will be
          visible to other users
        </p>
        <div className="form-group">
          <label>Username</label>
          <input className="form-control" placeholder="" />
        </div>
        <div className="sign-up__footer">
          <button className="btn btn-primary">Create profile</button>
        </div>
      </form>
    );
  }
}

// const InnerForm = ({values, errors, touched, handleChange, handleBlur, handleSubmit, isSubmitting}) => (
//   <form onSubmit={handleSubmit}>
//     <input
//       type="email"
//       name="email"
//       onChange={handleChange}
//       onBlur={handleBlur}
//       value={values.email}
//     />
//     {touched.email && errors.email && <div>{errors.email}</div>}
//     <input
//       type="password"
//       name="password"
//       onChange={handleChange}
//       onBlur={handleBlur}
//       value={values.password}
//     />
//     {touched.password && errors.password && <div>{errors.password}</div>}
//     <button type="submit" disabled={isSubmitting}>
//       Submit
//     </button>
//   </form>
// );

export default SignUpForm;
