import './SingUpFrom.scss';

import React from 'react';
import {filter, isEmpty, pick} from 'ramda';
import {withFormik} from 'formik';
import {validateField} from '../../services/validationService';
import classNames from 'classnames';
import PropTypes from 'prop-types';

const InnerForm = ({
  values,
  errors,
  touched,
  isValid,
  handleChange,
  handleBlur,
  handleSubmit,
  isSubmitting,
  error,
  loading
}) => (
  <form
    onSubmit={handleSubmit}
    className={classNames('sign-up__form', {
      'sing-up__form--disabled': loading
    })}>
    {error &&
      isEmpty(touched) && (
        <div className="alert alert-danger" role="alert">
          Form is invalid
        </div>
      )}
    <div className="upload-photo" />
    <h5 className="sign-up__form__title">Personal info</h5>
    <p className="sign-up__form__description">
      This information is private and will not be visible to other users
    </p>
    <div className="sign-up__form__name">
      <div className="row">
        <div className="col-md">
          <div className="form-group">
            <label>First name</label>
            <input
              className={classNames('form-control', {
                'is-invalid': touched.firstName && errors.firstName
              })}
              type="text"
              name="firstName"
              onChange={handleChange}
              onBlur={handleBlur}
              value={values.firstName}
            />
            {touched.firstName &&
              errors.firstName && <div className="invalid-feedback">{errors.firstName}</div>}
          </div>
        </div>
        <div className="col-md">
          <div className="form-group">
            <label>Last name</label>
            <input
              className={classNames('form-control', {
                'is-invalid': touched.lastName && errors.lastName
              })}
              type="text"
              name="lastName"
              onChange={handleChange}
              onBlur={handleBlur}
              value={values.lastName}
            />
            {touched.lastName &&
              errors.lastName && <div className="invalid-feedback">{errors.lastName}</div>}
          </div>
        </div>
      </div>
    </div>
    <div className="form-group">
      <label>Phone number</label>
      <small className="form-text text-muted">Enter your number</small>
      <input
        className={classNames('form-control', {
          'is-invalid': touched.phone && errors.phone
        })}
        type="text"
        name="phone"
        onChange={handleChange}
        onBlur={handleBlur}
        value={values.phone}
      />
      {touched.phone && errors.phone && <div className="invalid-feedback">{errors.phone}</div>}
    </div>
    <div className="form-group">
      <label>Address</label>
      <small className="form-text text-muted">
        Enter a postcode or address line. Only information about your city will be visible to other
        users
      </small>
      <input
        className={classNames('form-control', {
          'is-invalid': touched.address && errors.address
        })}
        type="text"
        name="address"
        onChange={handleChange}
        onBlur={handleBlur}
        value={values.address}
      />
      {touched.address &&
        errors.address && <div className="invalid-feedback">{errors.address}</div>}
    </div>
    <h5 className="sign-up__form__title">Public info</h5>
    <p className="sign-up__form__description">
      Your username is generated by the system. You can change it, this information will be visible
      to other users
    </p>
    <div className="form-group">
      <label>Username</label>
      <input
        className={classNames('form-control', {
          'is-invalid': touched.username && errors.username
        })}
        type="text"
        name="username"
        onChange={handleChange}
        onBlur={handleBlur}
        value={values.username}
      />
      {touched.username &&
        errors.username && <div className="invalid-feedback">{errors.username}</div>}
    </div>
    <div className="sign-up__footer">
      <button type="submit" className="btn btn-primary" disabled={isSubmitting || !isValid}>
        Create profile
      </button>
    </div>
  </form>
);

const SignUpForm = withFormik({
  mapPropsToValues: () => ({
    firstName: '',
    lastName: '',
    phone: '',
    address: '',
    username: ''
  }),
  validate: values => {
    const errors = {};
    const {firstName, lastName, phone, address, username} = values;

    errors.firstName = validateField(firstName, 'name');
    errors.lastName = validateField(lastName, 'name');
    errors.phone = validateField(phone, 'phoneNumber');
    errors.address = validateField(address, 'address');
    errors.username = validateField(username, 'username');

    return filter(n => n, errors);
  },
  handleSubmit: (values, {props, setSubmitting, setTouched}) => {
    const profile = pick(['firstName', 'lastName', 'phone', 'address', 'username'], values);
    props.onSubmit(profile).then(
      () => setSubmitting(false),
      () => {
        setSubmitting(false);
        setTouched({});
      }
    );
  }
})(InnerForm);

export default SignUpForm;

SignUpForm.propTypes = {
  loading: PropTypes.bool,
  error: PropTypes.any,
  onSubmit: PropTypes.func.isRequired
};
